_wandb:
    value:
        cli_version: 0.23.0
        e:
            3v2tpr32y99p95zvuiv4xbtnkvmhz4qz:
                args:
                    - --using_clip_features
                    - --using_hard_prompt
                    - --bs
                    - "32"
                    - --lr
                    - "5e-5"
                    - --epochs
                    - "100"
                    - --device
                    - cuda:0
                    - --clip_model
                    - BAAI/AltCLIP-m18
                    - --language_model
                    - NlpHUST/gpt2-vietnamese
                    - --num_layers
                    - "10"
                    - --continuous_prompt_length
                    - "10"
                    - --clip_project_length
                    - "10"
                    - --out_dir
                    - ./checkpoints/viecap_vietnamese
                    - --path_of_datasets
                    - annotations/uit_viic_entities_with_features.pkl
                    - --name_of_objects_vocabs
                    - vietnamese_entities
                    - --path_of_objects_vocabs
                    - src/config/vietnamese_entities.json
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "102128648192"
                        used: "57198424064"
                email: ldn.hitman.47@gmail.com
                executable: /DATA/van-n/.envs/conda-envs/viecap/bin/python
                git:
                    commit: da4cd8a7a69cd243c533fd24112cb09571d61cc9
                    remote: https://github.com/vanngthi/ViTrCap.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-b21508a1-a917-45d7-6c62-e7a11f172700
                host: vais
                memory:
                    total: "50309115904"
                os: Linux-6.8.0-84-generic-x86_64-with-glibc2.39
                program: /DATA/van-n/phenikaa/ViTrCap/train.py
                python: CPython 3.11.14
                root: /DATA/van-n/phenikaa/ViTrCap
                startedAt: "2025-11-21T07:40:11.341218Z"
                writerId: 3v2tpr32y99p95zvuiv4xbtnkvmhz4qz
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
            "3":
                - 3
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
bs:
    value: 32
clip_model:
    value: BAAI/AltCLIP-m18
clip_project_length:
    value: 10
continuous_prompt_length:
    value: 10
debug:
    value: false
device:
    value: cuda:0
disable_random_seed:
    value: false
epochs:
    value: 100
few_shot_ratio:
    value: 1
frozen_gpt:
    value: false
is_rn:
    value: false
language_model:
    value: NlpHUST/gpt2-vietnamese
lr:
    value: 5e-05
max_num_of_entities:
    value: 10
name_of_objects_vocabs:
    value: vietnamese_entities
noise_variance:
    value: 0.016
normalize_prefix:
    value: true
num_layers:
    value: 10
num_workers:
    value: 0
only_hard_prompt:
    value: false
out_dir:
    value: ./checkpoints/viecap_vietnamese
path_of_datasets:
    value: annotations/uit_viic_entities_with_features.pkl
path_of_objects_vocabs:
    value: src/config/vietnamese_entities.json
prefix:
    value: coco_prefix
prob_of_random_mask:
    value: 0.4
prompt_template_length:
    value: 5
random_mask:
    value: false
random_seed:
    value: 30
save_every:
    value: 1
soft_prompt_first:
    value: false
use_amp:
    value: false
using_clip_features:
    value: true
using_hard_prompt:
    value: true
